"""empty message

Revision ID: 119342c1739f
Revises: 46117a3db2a7
Create Date: 2022-09-01 01:44:06.358053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '119342c1739f'
down_revision = '46117a3db2a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'list_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'list_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
