"""empty message

Revision ID: 1f1126cd2e59
Revises: de981e7c9051
Create Date: 2022-09-01 02:07:13.613315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f1126cd2e59'
down_revision = 'de981e7c9051'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'completed',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'completed',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
