"""empty message

Revision ID: 3ca0b9d73653
Revises: 573a11bf261f
Create Date: 2022-08-31 04:13:49.223427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ca0b9d73653'
down_revision = '573a11bf261f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'completed',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'completed',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
