"""empty message

Revision ID: 579ea8bbc6f0
Revises: 609d105e2c3c
Create Date: 2022-09-01 01:47:19.538418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '579ea8bbc6f0'
down_revision = '609d105e2c3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'list_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'list_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
