"""empty message

Revision ID: 609d105e2c3c
Revises: f54545de8ef6
Create Date: 2022-09-01 01:45:46.051522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '609d105e2c3c'
down_revision = 'f54545de8ef6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'list_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.execute('UPDATE todos SET list_id = 1 WHERE list_id IS NULL')

    op.alter_column('todos','list_id',nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'list_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
