"""empty message

Revision ID: 745358bda4a2
Revises: 0f11d8c6405d
Create Date: 2022-08-27 02:28:16.813997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '745358bda4a2'
down_revision = '0f11d8c6405d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stuff', 'completed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stuff', 'completed',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
