"""empty message

Revision ID: dd1ada963283
Revises: 9e46dd902f5c
Create Date: 2022-08-27 01:09:40.146590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd1ada963283'
down_revision = '9e46dd902f5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stuff', sa.Column('completed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stuff', 'completed')
    # ### end Alembic commands ###
