"""empty message

Revision ID: a81fc9102f9a
Revises: 6767d86eaac3
Create Date: 2022-09-10 03:22:27.885485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a81fc9102f9a'
down_revision = '6767d86eaac3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('completed', sa.Boolean(), nullable=True))
    # when working on xisting date we do alter the column in migration file
    op.execute('UPDATE todos SET completed = False WHERE completed IS Null;')

    op.alter_column('todos','completed',nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'completed')
    # ### end Alembic commands ###
