"""empty message

Revision ID: 5f3642c1bc02
Revises: a4272c1f674e
Create Date: 2022-09-12 18:32:46.107320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f3642c1bc02'
down_revision = 'a4272c1f674e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('completed', sa.Boolean(), nullable=True))

    op.execute("UPDATE todos SET completed=False WHERE completed is NULL")
    # ### end Alembic commands ###

    op.alter_column('todos','completed',nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'completed')
    # ### end Alembic commands ###
